import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-hot-toast';
import { FaCalendarAlt, FaClock, FaMapMarkerAlt, FaMagic, FaMoneyBillWave, FaTimes, FaFilm, FaMusic, FaPlus, FaTrash } from "react-icons/fa";
import api from '../../services/api';

const CreateEventPage = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  
  // AI State
  const [showAiModal, setShowAiModal] = useState(false);
  const [aiKeywords, setAiKeywords] = useState("");
  const [aiLoading, setAiLoading] = useState(false);

  // Image State
  const [imageFile, setImageFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);

  // ✅ NEW: Event Type State
  const [eventType, setEventType] = useState("NORMAL"); // NORMAL or MOVIE

  // ✅ NEW: Seat Tier State for Movies
  const [seatTiers, setSeatTiers] = useState([
      { name: 'Standard', price: 0, startRow: 1, endRow: 5 }
  ]);

  const [formData, setFormData] = useState({
    title: '', date: '', time: '', location: '', category: 'Music', description: '',
    price: '', totalCapacity: '', isSeated: false, totalRows: '', totalCols: '', seatConfig: '' 
  });

  const handleChange = (e) => {
    const { name, value, type, checked } = e.target;
    setFormData(prev => ({ 
        ...prev, 
        [name]: type === 'checkbox' ? checked : value 
    }));
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImageFile(file);
      setPreviewUrl(URL.createObjectURL(file));
    }
  };

  // ✅ NEW: Seat Tier Management Functions
  const addSeatTier = () => {
      const lastTier = seatTiers[seatTiers.length - 1];
      setSeatTiers([...seatTiers, { 
          name: 'New Tier', 
          price: 0, 
          startRow: lastTier ? parseInt(lastTier.endRow) + 1 : 1, 
          endRow: lastTier ? parseInt(lastTier.endRow) + 5 : 5 
      }]);
  };

  const removeSeatTier = (index) => {
      if (seatTiers.length > 1) {
          const newTiers = seatTiers.filter((_, i) => i !== index);
          setSeatTiers(newTiers);
      }
  };

  const updateSeatTier = (index, field, value) => {
      const newTiers = [...seatTiers];
      newTiers[index][field] = value;
      setSeatTiers(newTiers);
  };

  // ✅ Generate Config String from Tiers
  const generateSeatConfig = () => {
      return seatTiers.map(t => `${t.startRow}-${t.endRow}:${t.price}:${t.name}`).join(',');
  };

  // ✅ Calculate Total Rows from Tiers
  const calculateTotalRows = () => {
      if (seatTiers.length === 0) return 0;
      return Math.max(...seatTiers.map(t => parseInt(t.endRow)));
  };

  const calculateMinPrice = (config) => {
    if (!config) return 0;
    try {
        const prices = config.split(',').map(rule => {
            const parts = rule.split(':'); 
            return parts.length >= 2 ? parseFloat(parts[1]) : Infinity;
        });
        const min = Math.min(...prices);
        return min === Infinity ? 0 : min;
    } catch { return 0; }
  };

  const handleAiGenerate = async () => {
    if (!formData.title || !formData.category) {
      toast.error("Please enter a Title and select a Category first.");
      return;
    }
    if (!aiKeywords.trim()) {
        toast.error("Please enter some keywords.");
        return;
    }

    setAiLoading(true);
    try {
      const payload = {
        title: formData.title,
        category: formData.category,
        keywords: aiKeywords
      };

      const response = await api.post('/api/ai/generate-description', payload);
      
      if (response.data && response.data.description) {
        setFormData(prev => ({ ...prev, description: response.data.description }));
        toast.success("✨ Description generated by AI!");
        setShowAiModal(false);
        setAiKeywords("");
      } else {
        toast.error("AI returned empty result.");
      }
    } catch (error) {
      console.error("AI Generation failed:", error);
      toast.error("Failed to generate description.");
    } finally {
      setAiLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    try {
        let finalImageUrl = "https://via.placeholder.com/800x400"; 
        if (imageFile) {
            const uploadData = new FormData();
            uploadData.append("file", imageFile);
            const uploadRes = await api.post('/api/images/upload', uploadData, {
                headers: { "Content-Type": "multipart/form-data" }
            });
            finalImageUrl = uploadRes.data.imageUrl; 
        }

        let safeTime = null;
        let finalPrice = 0;
        let finalSeatConfig = formData.seatConfig;
        let finalTotalRows = formData.totalRows;

        // ✅ LOGIC: Standard Event Validation
        if (eventType === "NORMAL") {
            safeTime = formData.time && formData.time.length === 5 
                            ? formData.time + ":00" 
                            : "10:00:00"; 

            if (formData.isSeated) {
                finalPrice = calculateMinPrice(formData.seatConfig);
                if (finalPrice === 0) {
                    toast.error("Please enter a valid Seat Configuration");
                    setLoading(false);
                    return;
                }
            } else {
                finalPrice = parseFloat(formData.price);
                if (!finalPrice || finalPrice <= 0) {
                    toast.error("Please enter a valid Ticket Price");
                    setLoading(false);
                    return;
                }
            }
        } 
        
        // ✅ LOGIC: Movie Event Validation (Auto-Generate Config)
        if (eventType === "MOVIE") {
            // Force Movie Category
            if (formData.totalCols <= 0) {
                 toast.error("Please enter Total Columns for the theater layout.");
                 setLoading(false);
                 return;
            }
            finalSeatConfig = generateSeatConfig();
            finalTotalRows = calculateTotalRows();
            
            // Check if user entered prices for tiers
            if (seatTiers.some(t => t.price <= 0)) {
                toast.error("Please set a price greater than 0 for all seat tiers.");
                setLoading(false);
                return;
            }
        }

        const payload = {
            title: formData.title,
            description: formData.description,
            category: eventType === "MOVIE" ? "Movies" : formData.category,
            location: formData.location,
            imageUrl: finalImageUrl, 
            organizerName: "Global Events", 
            
            eventType: eventType,

            // Conditional Fields
            date: eventType === "NORMAL" ? (formData.date || "2025-01-01") : null,
            time: eventType === "NORMAL" ? safeTime : null,
            
            seated: eventType === "NORMAL" ? formData.isSeated : true, // Movies always seated
            totalRows: eventType === "MOVIE" ? parseInt(finalTotalRows) : (formData.isSeated ? parseInt(formData.totalRows) : null),
            totalCols: parseInt(formData.totalCols) || 12, // Default 12 cols if missing
            seatConfig: eventType === "MOVIE" ? finalSeatConfig : (formData.isSeated ? formData.seatConfig : null),
            
            totalCapacity: eventType === "NORMAL" && !formData.isSeated ? parseInt(formData.totalCapacity) : null,
            price: eventType === "NORMAL" ? finalPrice : 0, 
        };

        await api.post('/api/events/create', payload); 
        toast.success(eventType === "MOVIE" ? "Movie Created! Now add Showtimes." : "Event Created Successfully! 🎉");
        
        navigate('/admin/events');

    } catch (error) {
        console.error("Create failed:", error);
        toast.error("Failed to create event. Check console.");
    } finally {
        setLoading(false);
    }
  };

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <h1 className="text-3xl font-bold text-gray-800 dark:text-white mb-8">Create New Event</h1>
      
      {/* EVENT TYPE TOGGLE */}
      <div className="flex justify-center mb-8 bg-gray-100 dark:bg-gray-800 p-2 rounded-full w-max mx-auto">
        <button 
            type="button"
            onClick={() => setEventType("NORMAL")}
            className={`flex items-center px-6 py-2 rounded-full text-sm font-bold transition-all ${
                eventType === "NORMAL" 
                ? "bg-blue-600 text-white shadow-md" 
                : "text-gray-500 hover:text-gray-700 dark:text-gray-400"
            }`}
        >
            <FaMusic className="mr-2" /> Standard Event
        </button>
        <button 
            type="button"
            onClick={() => setEventType("MOVIE")}
            className={`flex items-center px-6 py-2 rounded-full text-sm font-bold transition-all ${
                eventType === "MOVIE" 
                ? "bg-purple-600 text-white shadow-md" 
                : "text-gray-500 hover:text-gray-700 dark:text-gray-400"
            }`}
        >
            <FaFilm className="mr-2" /> Movie
        </button>
      </div>

      <form onSubmit={handleSubmit} className="bg-white dark:bg-gray-800 p-8 rounded-xl shadow-lg border border-gray-100 dark:border-gray-700 space-y-6">
        
        {/* Basic Info */}
        <div className="space-y-4">
            <div>
                <label className="block text-sm font-bold text-gray-700 dark:text-gray-300 mb-1">
                    {eventType === "MOVIE" ? "Movie Title" : "Event Title"}
                </label>
                <input type="text" name="title" value={formData.title} onChange={handleChange} className="w-full p-3 bg-gray-50 dark:bg-gray-700 border rounded-lg dark:text-white focus:ring-2 focus:ring-blue-500" required />
            </div>

            {/* HIDE DATE/TIME FOR MOVIES */}
            {eventType === "NORMAL" && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 animate-fadeIn">
                    <div>
                        <label className="block text-sm font-bold text-gray-700 dark:text-gray-300 mb-1">Date</label>
                        <div className="relative">
                            <FaCalendarAlt className="absolute left-3 top-3.5 text-gray-400" />
                            <input type="date" name="date" value={formData.date} onChange={handleChange} className="w-full p-3 pl-10 bg-gray-50 dark:bg-gray-700 border rounded-lg dark:text-white" required />
                        </div>
                    </div>
                    <div>
                        <label className="block text-sm font-bold text-gray-700 dark:text-gray-300 mb-1">Time</label>
                        <div className="relative">
                            <FaClock className="absolute left-3 top-3.5 text-gray-400" />
                            <input type="time" name="time" value={formData.time} onChange={handleChange} className="w-full p-3 pl-10 bg-gray-50 dark:bg-gray-700 border rounded-lg dark:text-white" required />
                        </div>
                    </div>
                </div>
            )}

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                    <label className="block text-sm font-bold text-gray-700 dark:text-gray-300 mb-1">Location</label>
                    <div className="relative">
                        <FaMapMarkerAlt className="absolute left-3 top-3.5 text-gray-400" />
                        <input type="text" name="location" value={formData.location} onChange={handleChange} className="w-full p-3 pl-10 bg-gray-50 dark:bg-gray-700 border rounded-lg dark:text-white" required />
                    </div>
                </div>
                <div>
                    <label className="block text-sm font-bold text-gray-700 dark:text-gray-300 mb-1">Category</label>
                    <select 
                        name="category" 
                        value={eventType === "MOVIE" ? "Movies" : formData.category} 
                        onChange={handleChange} 
                        disabled={eventType === "MOVIE"}
                        className="w-full p-3 bg-gray-50 dark:bg-gray-700 border rounded-lg dark:text-white disabled:opacity-60"
                    >
                        {eventType === "MOVIE" ? (
                            <option value="Movies">Movies</option>
                        ) : (
                            <>
                                <option value="Music">Music</option>
                                <option value="Technology">Technology</option>
                                <option value="Workshop">Workshop</option>
                                <option value="Sports">Sports</option>
                                <option value="Business">Business</option>
                                <option value="Others">Others</option>
                            </>
                        )}
                    </select>
                </div>
            </div>
        </div>

        {/* ✅ NEW: MOVIE PRICING & SEAT CONFIGURATOR */}
        {eventType === "MOVIE" && (
            <div className="p-6 bg-purple-50 dark:bg-gray-700/50 rounded-xl border border-purple-100 dark:border-gray-600 animate-fadeIn">
                 <h3 className="text-lg font-bold text-gray-800 dark:text-white mb-4 flex items-center">
                    <FaMoneyBillWave className="mr-2 text-purple-600" /> 
                    Seat Configuration & Pricing
                </h3>
                
                <div className="mb-6">
                    <label className="block text-sm font-bold mb-1 dark:text-gray-300">Total Columns per Row</label>
                    <input type="number" name="totalCols" value={formData.totalCols} onChange={handleChange} className="w-full p-3 border rounded-lg dark:bg-gray-700 dark:text-white" placeholder="e.g. 12 or 20" required />
                </div>

                <div className="space-y-4">
                    <label className="block text-sm font-bold dark:text-gray-300">Define Pricing Tiers (Rows)</label>
                    
                    {seatTiers.map((tier, index) => (
                        <div key={index} className="grid grid-cols-12 gap-2 items-end bg-white dark:bg-gray-800 p-3 rounded-lg shadow-sm border border-gray-200 dark:border-gray-600">
                            <div className="col-span-4">
                                <label className="text-xs text-gray-500 mb-1 block">Tier Name</label>
                                <input type="text" value={tier.name} onChange={(e) => updateSeatTier(index, 'name', e.target.value)} className="w-full p-2 text-sm border rounded dark:bg-gray-700 dark:text-white" placeholder="VIP" />
                            </div>
                            <div className="col-span-2">
                                <label className="text-xs text-gray-500 mb-1 block">Start Row</label>
                                <input type="number" value={tier.startRow} onChange={(e) => updateSeatTier(index, 'startRow', e.target.value)} className="w-full p-2 text-sm border rounded dark:bg-gray-700 dark:text-white" />
                            </div>
                            <div className="col-span-2">
                                <label className="text-xs text-gray-500 mb-1 block">End Row</label>
                                <input type="number" value={tier.endRow} onChange={(e) => updateSeatTier(index, 'endRow', e.target.value)} className="w-full p-2 text-sm border rounded dark:bg-gray-700 dark:text-white" />
                            </div>
                            <div className="col-span-3">
                                <label className="text-xs text-gray-500 mb-1 block">Price (₹)</label>
                                <input type="number" value={tier.price} onChange={(e) => updateSeatTier(index, 'price', e.target.value)} className="w-full p-2 text-sm border rounded dark:bg-gray-700 dark:text-white" placeholder="500" />
                            </div>
                            <div className="col-span-1 flex justify-center pb-2">
                                <button type="button" onClick={() => removeSeatTier(index)} className="text-red-500 hover:text-red-700">
                                    <FaTrash size={14} />
                                </button>
                            </div>
                        </div>
                    ))}

                    <button type="button" onClick={addSeatTier} className="text-sm flex items-center text-purple-600 font-semibold hover:text-purple-800 mt-2">
                        <FaPlus className="mr-1" /> Add Another Tier
                    </button>
                    
                    <div className="mt-4 p-3 bg-gray-100 dark:bg-gray-900 rounded text-xs font-mono text-gray-600 dark:text-gray-400">
                        Generated Config: {generateSeatConfig()}
                    </div>
                </div>
            </div>
        )}

        {/* Standard Event Pricing (OLD LOGIC PRESERVED) */}
        {eventType === "NORMAL" && (
            <div className="p-6 bg-blue-50 dark:bg-gray-700/50 rounded-xl border border-blue-100 dark:border-gray-600 animate-fadeIn">
                <div className="flex justify-between items-center mb-6">
                    <h3 className="text-lg font-bold text-gray-800 dark:text-white flex items-center">
                        <FaMoneyBillWave className="mr-2 text-blue-600" /> 
                        Pricing & Capacity
                    </h3>
                    <label className="flex items-center cursor-pointer select-none">
                        <span className="mr-3 text-sm font-medium text-gray-600 dark:text-gray-300">
                            {formData.isSeated ? "💺 Seated Event" : "🎫 General Admission"}
                        </span>
                        <div className="relative">
                            <input type="checkbox" name="isSeated" checked={formData.isSeated} onChange={handleChange} className="sr-only peer" />
                            <div className="w-11 h-6 bg-gray-200 peer-focus:outline-none rounded-full peer dark:bg-gray-700 peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"></div>
                        </div>
                    </label>
                </div>

                {formData.isSeated ? (
                    <div className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-bold mb-1 dark:text-gray-300">Total Rows</label>
                                <input type="number" name="totalRows" value={formData.totalRows} onChange={handleChange} className="w-full p-3 border rounded-lg dark:bg-gray-700 dark:text-white" placeholder="e.g. 10" />
                            </div>
                            <div>
                                <label className="block text-sm font-bold mb-1 dark:text-gray-300">Total Columns</label>
                                <input type="number" name="totalCols" value={formData.totalCols} onChange={handleChange} className="w-full p-3 border rounded-lg dark:bg-gray-700 dark:text-white" placeholder="e.g. 12" />
                            </div>
                        </div>
                        <div>
                            <label className="block text-sm font-bold mb-1 dark:text-gray-300">Tiered Pricing Configuration</label>
                            <textarea name="seatConfig" rows="3" value={formData.seatConfig} onChange={handleChange} className="w-full p-3 border rounded-lg font-mono text-sm dark:bg-gray-700 dark:text-white" placeholder="Format: RowStart-RowEnd:Price:Label&#10;Example:&#10;1-2:1000:VIP&#10;3-5:500:Gold&#10;6-10:200:Silver"></textarea>
                        </div>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div>
                            <label className="block text-sm font-bold mb-1 dark:text-gray-300">Total Capacity</label>
                            <input type="number" name="totalCapacity" value={formData.totalCapacity} onChange={handleChange} className="w-full p-3 border rounded-lg dark:bg-gray-700 dark:text-white" placeholder="Total tickets available" />
                        </div>
                        <div>
                            <label className="block text-sm font-bold mb-1 dark:text-gray-300">Ticket Price (₹)</label>
                            <input type="number" name="price" value={formData.price} onChange={handleChange} className="w-full p-3 border rounded-lg dark:bg-gray-700 dark:text-white" placeholder="0.00" />
                        </div>
                    </div>
                )}
            </div>
        )}

        {/* Description & AI Button */}
        <div>
            <div className="flex justify-between items-center mb-2">
                <label className="block text-sm font-bold text-gray-700 dark:text-gray-300">Description</label>
                <button type="button" onClick={() => setShowAiModal(true)} className="text-xs bg-purple-100 text-purple-700 px-3 py-1 rounded-full flex items-center hover:bg-purple-200">
                    <FaMagic className="mr-1"/> AI Generate
                </button>
            </div>
            <textarea name="description" rows="5" value={formData.description} onChange={handleChange} className="w-full p-3 bg-gray-50 dark:bg-gray-700 border rounded-lg dark:text-white" required></textarea>
        </div>

        {/* Image Upload */}
        <div className="mb-6">
            <label className="block text-gray-700 dark:text-gray-300 text-sm font-bold mb-2">Event Banner</label>
            <input type="file" accept="image/*" onChange={handleFileChange} className="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-blue-50 file:text-blue-700 hover:file:bg-blue-100" />
            {previewUrl && (
                <div className="mt-4 relative h-48 w-full rounded-lg overflow-hidden border border-gray-300">
                    <img src={previewUrl} alt="Preview" className="w-full h-full object-cover" />
                </div>
            )}
        </div>

        <button type="submit" disabled={loading} className="w-full bg-blue-600 text-white font-bold py-4 rounded-xl hover:bg-blue-700 transition shadow-lg">
            {loading ? "Creating..." : eventType === "MOVIE" ? "🎬 Save Movie & Continue" : "🚀 Create Event"}
        </button>
      </form>

      {/* AI Modal */}
      {showAiModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-xl w-96 relative animate-fadeIn">
            <button onClick={() => setShowAiModal(false)} className="absolute top-3 right-3 text-gray-400 hover:text-gray-600">
              <FaTimes />
            </button>
            <h3 className="text-xl font-bold text-gray-800 dark:text-white mb-4 flex items-center">
              <FaMagic className="mr-2 text-purple-600" /> Generate Description
            </h3>
            <p className="text-gray-500 dark:text-gray-400 text-sm mb-4">
              Using Title: <b>{formData.title}</b>
            </p>
            <div className="mb-4">
              <label className="block text-gray-700 dark:text-gray-300 mb-2 text-sm">Enter Keywords (comma separated)</label>
              <input type="text" value={aiKeywords} onChange={(e) => setAiKeywords(e.target.value)} placeholder="e.g., exciting, live band, fun" className="w-full p-2 border rounded dark:bg-gray-700 dark:text-white" />
            </div>
            <button onClick={handleAiGenerate} disabled={aiLoading} className="w-full bg-purple-600 text-white py-2 rounded hover:bg-purple-700 transition">
              {aiLoading ? "Generating..." : "Generate"}
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default CreateEventPage;